server:
  port: 9090

logging:
  path: ./logs/spring-boot-logger.lo

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${MCSVC_EUREKA_HOST_1_URL}
    healthcheck:
      enabled: true

