server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true