version: '3'
services:

  #Eureka Service
  discovery:
    container_name: mcsvc-infra-eureka-service
    image: jbprek/mcsvc-infra-eureka-service:latest
    ports:
      - "8761:8761"
    environment:
      - EUREKA_HOST
      - EUREKA_URL
    networks:
      - discovery
    restart: on-failure

  #Spring cloud config server
  config:
    container_name: mcsvc-infra-config-service
    image: jbprek/mcsvc-infra-config-service:latest
    ports:
      - "8888:8888"
    depends_on:
      - discovery
    environment:
      - EUREKA_URL
      - CONFIG_GIT_URL
      - CONFIG_GIT_USERNAME
      - CONFIG_GIT_PASSWORD
      - CONFIG_KEYSTORE_LOCATION
      - CONFIG_KEYSTORE_PASSWORD
      - CONFIG_KEYSTORE_ALIAS
      - CONFIG_KEYSTORE_SECRET
    networks:
      - discovery
    restart: on-failure

    #Codecentic Spring Boot Admin
  admin:
    container_name: mcsvc-infra-admin-service
    image: jbprek/mcsvc-infra-admin-service:latest
    ports:
      - "9000:9000"
    depends_on:
      - discovery
      - config
    environment:
      - EUREKA_URL
      - CONFIG_GIT_URL
    networks:
      - discovery
    restart: on-failure

networks:
  discovery:



