server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance: ${EUREKA_HOST:localhost}
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  server:
    enable-self-preservation: false

